#!/bin/bash
for file in *.html; do if [! -e "alx-system_engineering-devops/0x00-shell_basics/$file"] || [ "$file" -nt "alx-system_engineering-devops/0x00-shell_basics/$file" ]; then cp "$file" "alx-system_engineering-devops/0x00-shell_basics/"; done
